### ISSUE TITLE
rosserial_esp32 not found

### ISSUE THREAD

**Issue by BirBDey** [sachin0x18/rosserial_esp32#5]
Hi,
When I try to run your command 
`"rosrun rosserial_esp32 make_libraries.py $IDF_PATH/components/"`
I get an error saying that "rosserial_esp32 not found". 
Any clue on how to fix this issue?
Thanks
PS: I have tried to do "Rospack profile" no luck. I have also done catkin_make before doing anything.

**Comment by sachin0x18** [comment]
Hi BirBDey,

Where have you cloned rosserial_esp32 ? It should be placed in your catkin workspace folder (catkin_ws/src).

If it is already placed in your catkin workspace then please check if you have added it to your ROS environment (`source catkin_ws/devel/setup.bash`)

**Comment by sachin0x18** [comment]
Closing this issue. Feel free to re-open this if you face any difficulties
