### ISSUE TITLE
installation of esp-idf alongside ROS Noetic

### ISSUE THREAD

**Issue by wouter-heerwegh** [sachin0x18/rosserial_esp32#6]
Hi @sachin0x18,

I've been trying to install esp-idf while having ROS Noetic installed but I can't seem to get it working. ROS Noetic uses pyparsing 2.4.6 (installed via apt install python3-pyparsing) and cannot be uninstalled via pip. When I create a python virtual environment, it is still able to find the version 2.4.6.

Have you had the same problems? And if so, how did you solve them?

**Comment by sachin0x18** [comment]
Hi @wouter-heerwegh,

I haven't tried this but this seems to be some (mis)configuration problem. IDF usually creates a fresh virtual environment (https://github.com/espressif/esp-idf/blob/master/install.sh) and uses the same (https://github.com/espressif/esp-idf/blob/master/export.sh) so ideally you should not be seeing this error. 

Have you tried configuring IDF in a separate terminal window and ROS Noetic in a different terminal ? Do you still see the same issue ?

**Comment by wouter-heerwegh** [comment]
Hi @sachin0x18,

Yes, I still had the same problem. For some reason, I can still find pyparsing in a fresh virtual environment (even without sourcing ros). At the moment I'm running esp-odf in a docker container, but that is really inconvenient.

Are you using another version of ros?

**Comment by wouter-heerwegh** [comment]
Forgot that I still had something in my `.bashrc` file that was appending my python path. Removed that and now it just works.
